fix: Undefined record for window causing backtrace
pop-os/gnome-shell pull request #110
Opened 2022-05-27 14:48 UTC by mmstick

As seen in https://github.com/pop-os/shell/issues/1453, fixes this backtrace which could be breaking other behavior in the shell:

```
JS ERROR: TypeError: record is undefined
_syncStacking@resource:///org/gnome/shell/ui/workspaceAnimation.js:81:13
```

2022-05-27 16:09 UTC, n3m0-22 requested changes
I was able to recreate issues [#1453](https://github.com/pop-os/shell/issues/1453) and [#345](https://github.com/pop-os/cosmic/issues/345). This does seem to fix them, but I found two other similar condition that can cause this same sort of freeze.

Steps to reproduce:

These must be done in an app window they do not happen on the desktop.

First

1. Hold down left mouse button or touch pad
2. Do not release left mouse button or touch pad
3. Press Super key
4. Release the Super key
5. Press Super key again
6. Release left mouse button or touch pad

Second

1. Hold down right mouse button or touch pad
2. Do not release left mouse button or touch pad
3. Press Super key
4. Release right mouse button or touch pad

Both of these can also on occasion cause the keyboard to become unresponsive as well. This will happen with tiling on or off, and disabling pop-shell has no effect.

2022-05-27 16:11 UTC, mmstick commented
That requires https://github.com/pop-os/shell/pull/1454

2022-05-27 16:14 UTC, n3m0-22 approved these changes
Yes my mistake. Thanks for bringing that to my attention. That does fix it. This looks good.

2022-06-03 14:07 UTC, jackpot51 approved these changes

2022-06-03 14:07 UTC, merged